# ===========================
# Author: wqn
# Email: wangqn@tellhow.com
# Created: 20260320
# ===========================

from .api_registry import (
    APIProvider,
    clear_api_providers,
    get_api_provider,
    get_api_providers,
    register_api_provider,
    unregister_api_providers,
)
from .backend import CompleteOptions, EchoBackend, LLMBackend, ScriptedBackend
from .env_api_keys import get_env_api_key
from .event_stream import AssistantMessageEventStream, emit_assistant_message_events
from .models import calculate_cost, supports_xhigh
from .overflow import get_overflow_patterns, is_context_overflow
from .providers import (
    HTTPRequestError,
    AnthropicOptions,
    OpenAICompletionsOptions,
    build_base_options,
    clamp_reasoning,
    is_retryable_error,
    parse_retry_after_ms,
    register_built_in_api_providers,
    reset_api_providers,
    request_with_retry,
    stream_anthropic,
    stream_openai_completions,
    stream_simple_anthropic,
    stream_simple_openai_completions,
)
from .stream import complete, complete_simple, stream, stream_simple
from .types import (
    AssistantMessage,
    AssistantMessageEvent,
    CacheRetention,
    LLMContext,
    Message,
    Model,
    ModelCost,
    SimpleStreamOptions,
    StreamOptions,
    ThinkingLevel,
    ToolResultMessage,
    Transport,
    Usage,
    UsageCost,
    UserMessage,
    text_block,
    thinking_block,
    tool_call_block,
)

__all__ = [
    "APIProvider",
    "AnthropicOptions",
    "AssistantMessage",
    "AssistantMessageEvent",
    "AssistantMessageEventStream",
    "CacheRetention",
    "CompleteOptions",
    "EchoBackend",
    "HTTPRequestError",
    "LLMBackend",
    "LLMContext",
    "Message",
    "Model",
    "ModelCost",
    "OpenAICompletionsOptions",
    "ScriptedBackend",
    "SimpleStreamOptions",
    "StreamOptions",
    "ThinkingLevel",
    "ToolResultMessage",
    "Transport",
    "Usage",
    "UsageCost",
    "UserMessage",
    "build_base_options",
    "calculate_cost",
    "clamp_reasoning",
    "clear_api_providers",
    "complete",
    "complete_simple",
    "emit_assistant_message_events",
    "get_api_provider",
    "get_api_providers",
    "get_env_api_key",
    "get_overflow_patterns",
    "is_context_overflow",
    "is_retryable_error",
    "parse_retry_after_ms",
    "register_api_provider",
    "register_built_in_api_providers",
    "reset_api_providers",
    "request_with_retry",
    "stream",
    "stream_anthropic",
    "stream_openai_completions",
    "stream_simple",
    "stream_simple_anthropic",
    "stream_simple_openai_completions",
    "supports_xhigh",
    "text_block",
    "thinking_block",
    "tool_call_block",
    "unregister_api_providers",
]
